<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>PlaytimeTimers</AssemblyName>
    <RootNamespace>Martijn.PlaytimeTimers</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <ValheimInfoFile>$(MSBuildProjectDirectory)\info</ValheimInfoFile>
    <ValheimDirFromInfo Condition="'$(ValheimDir)' == '' and Exists('$(ValheimInfoFile)')">$([System.Text.RegularExpressions.Regex]::Match($([System.IO.File]::ReadAllText('$(ValheimInfoFile)')), '(?m)^ValheimDir=(.*)$').Groups[1].Value)</ValheimDirFromInfo>
    <ValheimDirFromInfo Condition="'$(ValheimDirFromInfo)' != ''">$([System.String]::Copy('$(ValheimDirFromInfo)').Trim())</ValheimDirFromInfo>
    <ValheimDir Condition="'$(ValheimDir)' == '' and '$(ValheimDirFromInfo)' != ''">$(ValheimDirFromInfo)</ValheimDir>
    <ValheimDir Condition="'$(ValheimDir)' == ''">C:\Program Files (x86)\Steam\steamapps\common\Valheim</ValheimDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>..\..\core\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>..\..\core\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(ValheimDir)\valheim_Data\Managed\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ValheimDir)\valheim_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(ValheimDir)\valheim_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(ValheimDir)\valheim_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(ValheimDir)\valheim_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
